require("conf.packer")
require("conf.cmp")
require("conf.lsp-config")
require("conf.telescope")
require("conf.lualine")
require("conf.nvim-colorizer")
require("conf.gitsigns")
require("conf.bufferline")
require("conf.nvimtree_new")
require("conf.autopairs")
require("conf.treesitter")
require("conf.comment")
require("conf.null-ls")
require("conf.catppuccin")
require("conf.mason")
require("conf.luasnip")
require("conf.harpoon")
require("conf.hop")
-- require("conf.noneckpain")
-- require("conf.onedarkpro")
